services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: harmony-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@harmonysocial.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - harmony-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: harmony-azurite
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --debug /data/debug.log
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - azurite_data:/data
    networks:
      - harmony-network

  mailpit:
    image: axllent/mailpit:edge
    container_name: mailpit-docker
    ports:
      - "8025:8025" # Puerto externo corregido
      - "1025:1025" # Puerto externo corregido
    networks:
      - harmony-network

  postgre_db:
    image: postgres
    container_name: harmony-postgres
    environment:
      POSTGRES_USER: harmony_user
      POSTGRES_PASSWORD: harmony_password
      POSTGRES_DB: harmonysocial
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - harmony-network

  mongo_db:
    image: mongo:7
    container_name: harmony-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27069:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - harmony-network

  mongo-express:
    image: mongo-express:1.0
    container_name: harmony-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db # ‚Üê Nombre del servicio de MongoDB
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: mongoexrootpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    networks:
      - harmony-network
    depends_on:
      - mongo_db

volumes:
  pgadmin_data:
  azurite_data:
  pgdata:
  mongodata:

networks:
  harmony-network:
    driver: bridge
